# -*- coding: utf-8 -*-
# Thesis draft v2 content. Markup:
#   {KEY} or {KEY1,KEY2}  -> IEEE citation, numbered by first appearance
#   ^^text^^              -> yellow highlight: claim carried over from the earlier draft, not yet checked against the source
#   **text**              -> bold
# Block types: ('title',..), ('meta',..), ('h1',..), ('h2',..), ('h3',..), ('p',..), ('bullets',[..]), ('numbered',[..]),
#              ('table', caption, [header], [[row],...], [col widths in twips]), ('note',..), ('pagebreak',)

TITLE = "Quantum-Optimised Generation of Operational Design Domain Boundary Test Scenarios, Traceably Derived from Safety Requirements for Automated Driving Systems"

B = []
A = B.append

# ---------------- Front matter ----------------
A(('title', TITLE))
A(('meta', "Saadia Sadaf (SP24-PCS-002)"))
A(('meta', "Doctor of Philosophy in Computer Science"))
A(('meta', "Department of Computer Science, COMSATS University Islamabad"))
A(('meta', "Supervisor: Prof. Dr. Manzoor Ilahi Tamimy"))
A(('meta', "Co-supervisor: Prof. Dr. Majid Iqbal Khan"))
A(('meta', "September 2026"))
A(('pagebreak',))

A(('h1', "Abstract"))
A(('p', "Automated driving systems continue to show safety-relevant failures after deployment, and several recent investigations concern behaviour at or beyond the limits of a system's Operational Design Domain (ODD), the set of conditions under which it is designed to operate. A current example is NHTSA Engineering Analysis EA26002, opened in March 2026, which concerns the failure of a driver-assistance system's degradation-detection function to detect and warn under reduced roadway visibility {D2}. Regulation now requires that an automated driving system recognise its ODD conditions and boundaries and respond when they are no longer fulfilled {C37}, yet published methods either formalise the ODD without deriving it from stated safety requirements {D10,C1}, or generate test scenarios from sources other than safety requirements, such as crash reports {C23} or traffic rules {C24}, without optimised selection of the scenarios to run."))
A(('p', "This thesis develops and evaluates a two-phase method. Phase A extracts ODD boundary predicates (dimension, variable, operator, threshold and unit) from natural-language safety requirements and stores a trace link from each predicate to its source requirement. It is modelled on published requirement-formalisation pipelines {C19,C34} and evaluated on a corpus of real regulatory requirements annotated independently by two people. Phase B formulates the selection of boundary test scenarios as a Quadratic Unconstrained Binary Optimization (QUBO) problem, solved with quantum annealing and the Quantum Approximate Optimization Algorithm (QAOA), and compares the result with classical baselines that include combinatorial, search-based and random testing {C33}. The evaluation asks how accurately predicates can be extracted, whether quantum-optimised scenario sets match classical ones on coverage and fault detection, what they cost to compute, and whether every selected scenario remains traceable to a requirement when that requirement changes."))
A(('p', "A preliminary feasibility study demonstrated that both phases can be realised with openly available tools and established two design requirements: rule-based extraction fell from 80% accuracy on the sentences from which its rules were derived to 28% on unseen sentences, which motivates a trained pipeline evaluated on a real corpus, and the scenario-selection objective must reward coverage explicitly. Consistent with the closest published work, the thesis does not presuppose that quantum methods outperform classical ones. Its contributions are a traceable link from stated safety requirements to selected verification scenarios, a public annotated requirements corpus, and a rigorous empirical assessment of where quantum optimisation does and does not offer benefit for this class of problem."))
A(('h1', "Declaration on the Use of Generative AI Tools"))
A(('p', "In preparing this thesis, I used generative AI tools to assist with verifying bibliographic records against publisher and official sources, with language editing, and with developing code for the preliminary feasibility study reported in Chapter 4. I checked every source cited in this thesis against its original record. The research design, analysis, interpretation and conclusions are my own. No AI system produced gold-standard annotations or evaluation results."))
A(('h1', "Lay Summary"))
A(('p', "Self-driving and driver-assistance systems are designed to work only under certain conditions, such as good visibility or marked lanes. Some real crashes have happened when those conditions were no longer met. Safety rules for these vehicles are written in ordinary language, so it is hard to check automatically that testing actually covers the conditions the rules describe. This research builds a tool that reads safety rules, picks out the conditions they set (for example \"visibility below a threshold\"), and keeps a record of which rule each condition came from. It then chooses a small set of test situations that cover those conditions, and compares doing this with quantum computing against standard methods. The aim is not to prove that a vehicle is perfectly safe, but to make testing traceable to the safety rules and to establish rigorously whether quantum computing helps."))
A(('pagebreak',))

# ---------------- Chapter 1 ----------------
A(('h1', "Chapter 1: Introduction"))
A(('h2', "1.1 Background"))
A(('p', "Driving automation is described by SAE J3016, which defines the levels of automation and the term Operational Design Domain {D44}. Systems at these levels are now deployed at scale, and their safety is argued under ISO 26262 for functional safety {D40} and ISO 21448 for the safety of the intended functionality (SOTIF) {D41}. For systems that depend on machine-learned perception, full formal verification remains out of reach: a recent survey of formal verification for vision-based autonomous systems states that \"a DNN can have billions of parameters, which precludes formal verification for most realistic, state-of-the-art networks\", and that the assurances existing techniques give \"are only valid when the deployed system stays within a narrow operational design domain\" {D8}. The ODD is therefore the natural boundary of what can be verified, and the place where verification effort is most needed."))
A(('p', "Scenario-based testing is the main practical alternative to distance-based road testing {C21}. It faces a coverage problem: one analysis estimated a gap of \"around one order of magnitude\" between the test coverage needed for highly automated vehicles and the coverage that is feasible {C31}. Choosing which scenarios to run is therefore itself an optimisation problem, and one that recent work has begun to formulate for quantum annealers and gate-based quantum algorithms {D17,D18,D19,C14}."))

A(('h2', "1.2 Problem Statement"))
A(('p', "Despite internal validation and simulation-based testing, automated driving and driver-assistance systems continue to show safety-relevant failures after deployment. Several recent cases concern the boundary of the system's operating conditions: the system either did not recognise that those conditions had degraded, or did not respond adequately when they did. At the same time, the requirement that a system recognise and respond to its ODD boundaries is now written into regulation {C37}. What is missing is a documented, evaluated method that starts from stated safety requirements, derives the ODD boundary conditions they impose in a traceable form, and uses those conditions to select the scenarios needed to test that boundary. This thesis addresses that gap."))
A(('p', "Table 1.1 summarises the incident record used to motivate the thesis. Each entry is limited to what the cited primary or official source states."))
A(('table', "Table 1.1. Incident record motivating the thesis (official sources)",
   ["Case", "Date", "What the source states", "Relevance to ODD boundaries"],
   [["NHTSA EA26002 (Tesla FSD)", "Opened 18 Mar 2026", "Upgraded from PE24031; about 3,203,754 vehicles; 9 crashes including 1 fatality; alleged failure of the degradation-detection system to detect a degraded state and warn the driver under reduced roadway visibility such as glare and airborne obscurants {D2}", "Direct: failure at a visibility boundary. Primary case study"],
    ["NTSB, Ford BlueCruise", "Report 31 Mar 2026", "Two fatal crashes; automation overreliance contributed; gaps included ineffective driver monitoring and the ability to disable automatic emergency braking while the system was engaged {D1}", "Indirect: operating-condition monitoring of the driver"],
    ["NTSB HWY26FH008 (Waymo)", "23 Jan 2026", "Automated vehicle travelling at 17 mph struck a 9-year-old pedestrian in a Santa Monica school zone; minor injuries; investigation ongoing {D7}", "School-zone conditions as part of the ODD"],
    ["Waymo recall 25E-084", "Dec 2025", "Software recall concerning the vehicles' behaviour around stopped school buses {WAYMOREC}", "Scenario class (school buses) missing from validation"],
    ["NHTSA consent order (Cruise)", "30 Sep 2024", "Penalty for incomplete crash reporting {D4}", "Context only: a reporting, not a perception, finding"]],
   [2000, 1300, 4000, 2060]))
A(('p', "The NTSB and NHTSA findings concern specific systems and do not show that any manufacturer lacked a requirements process. They show that failures cluster at operating-condition boundaries, which is where this thesis concentrates. The Florida jury verdict of August 2025 against Tesla concerning a fatal Autopilot crash {D3} illustrates the legal consequences that such failures can carry."))

A(('h2', "1.3 Aim, Objectives and Research Questions"))
A(('p', "**Aim.** To develop and evaluate a method that derives traceable ODD boundary predicates from natural-language safety requirements and uses them to drive quantum-optimised selection of verification scenarios for automated driving systems."))
A(('p', "**Objectives.**"))
A(('numbered', [
    "Build and publish a corpus of real automotive safety requirements, annotated independently by two people for ODD dimension, variable, operator, threshold and unit.",
    "Develop and evaluate a pipeline that extracts ODD boundary predicates from those requirements and stores trace links to their sources.",
    "Formulate ODD boundary scenario selection as a QUBO problem that rewards coverage and traceability, and solve it with quantum annealing and QAOA.",
    "Compare the quantum-optimised scenario sets with classical baselines on coverage, fault detection and computational cost, reporting all outcomes, including the absence of any significant difference.",
    "Test whether trace links from requirement to selected scenario survive a change to the source requirement."]))
A(('p', "**Research questions.** RQ1: What fraction of real automotive safety requirements can be correctly mapped to a traceable ODD boundary predicate? RQ2: Do QUBO-optimised scenario sets match or exceed classical baselines on ODD coverage and fault detection? RQ3: What is the computational cost of the quantum approach relative to classical baselines, and at what problem size do hardware limits force decomposition? RQ4: Can every selected scenario be traced to a source requirement, and does that trace survive a change to the requirement?"))

A(('h2', "1.4 Contributions"))
A(('bullets', [
    "An annotated, public corpus of real regulatory safety requirements labelled for ODD boundary predicates, with inter-annotator agreement reported.",
    "A requirement-to-ODD-predicate extraction method with stored trace links, evaluated on held-out and held-out-source splits.",
    "A QUBO formulation of ODD boundary scenario selection with an explicit coverage and traceability term, and its first evaluation in the automated-driving ODD domain.",
    "An empirical account of where quantum optimisation does and does not help for this problem, compared against the classical baselines used in the same domain."]))
A(('p', "Section 2.10 positions these contributions against the closest published work."))

A(('h2', "1.5 Scope and Limitations"))
A(('p', "The thesis addresses traceable scenario selection at ODD boundaries. It does not claim a formal proof of vehicle safety. The case study is reconstructed from public filings about EA26002 and is not a replication of any manufacturer's system. Quantum experiments use simulators and, where access allows, publicly available cloud hardware; large-scale hardware evaluation is outside the resources of a doctoral project. The requirements corpus is drawn from public regulations and documents rather than proprietary manufacturer data."))
A(('h2', "1.6 Thesis Structure"))
A(('p', "Chapter 2 reviews the literature using the method described in Section 2.1 and summarises the reviewed studies in Table 2.2. Chapter 3 presents the methodology: the corpus, the two phases and the evaluation plan. Chapter 4 reports a preliminary feasibility study that informed the design of both phases. Chapter 5 presents the full evaluation of both phases and the case study against the research questions, and Chapter 6 concludes the thesis and outlines future research."))
A(('pagebreak',))

# ---------------- Chapter 2 ----------------
A(('h1', "Chapter 2: Literature Review"))
A(('h2', "2.1 Review Method"))
A(('p', "I conducted this review as a focused, question-driven literature synthesis informed by the guidelines of Kitchenham and Charters for systematic reviews in software engineering {KITCH} and the mapping-study guidelines of Petersen et al. {PETER}. Five mapping questions structure the review: MQ1, how ODD boundaries are specified, formalised or monitored; MQ2, how natural-language automotive requirements are formalised automatically; MQ3, which methods generate or select test scenarios for automated driving and whether they preserve traceability; MQ4, how quantum and Ising-based optimisation has been applied to test generation, selection and minimisation; and MQ5, which combinations remain unaddressed."))
A(('p', "Sources were identified through structured keyword searches combining terms for the automated-driving domain, the ODD, safety requirements, scenario generation and quantum optimisation, complemented by backward and forward citation tracing from the most relevant studies {WOHLIN}. Studies were included if they were peer-reviewed publications, official standards or regulatory documents, or openly available preprints central to MQ4 or MQ5, and if they addressed at least one mapping question. Each included source was verified against its publisher or official record, and every quantitative figure reported in this chapter is taken directly from the cited source. The resulting body of literature is analysed thematically in Sections 2.2 to 2.9, synthesised against the research gap in Section 2.10, and summarised study by study in Table 2.2."))

A(('h2', "2.2 Formal Verification of Automated Driving and Perception"))
A(('p', "Model checking, whose origins Clarke describes in {D21}, and deductive verification remain the reference methods for proving software correct. Their application to autonomous systems has been surveyed for robotic systems {S64}, and specification patterns have been proposed for robotic missions {S63}. For perception, Mitra et al. survey six technique families: probabilistic abstractions for perception, symbolic model checking with perception contracts, compositional verification with assumption generation, mathematical models of cameras and environments, generative models, and statistical model checking with runtime verification {D8}. They note that one camera-based technique \"already takes about an hour for the largest environments considered\", and that the assurances such techniques afford hold only within a narrow operational design domain {D8}."))
A(('p', "Deductive verification continues to advance, for example through combining deductive and automatic verification {S27} and proof reuse for product lines {S24}, and practitioner studies examine the obstacles to its adoption {S25}; a history of the field is given by Hähnle and Huisman {S23}. The annual software verification competition documents the state of automatic verification tools {S8}. None of this work removes the tractability limit for machine-learned perception, which is why this thesis targets verification scenarios at the ODD boundary rather than a correctness proof."))
A(('p', "A parallel line of work defines safety for driving behaviour directly. Responsibility-Sensitive Safety proposes \"a white-box, interpretable, mathematical model for safety assurance\" for driving manoeuvres {D67}. It shows that formal guarantees are achievable for precisely specifiable behaviours, while leaving the perception and operating-condition boundary open."))

A(('h2', "2.3 The Operational Design Domain: Standards, Formalisation and Monitoring"))
A(('p', "The term ODD is defined in SAE J3016 {D44}. Two taxonomies define its content: BSI PAS 1883 {D66} and ISO 34503:2023, which specifies the ODD in the context of test scenarios for automated driving systems {C6}. ASAM OpenODD, released as version 1.0.0 in April 2025, provides a machine-interpretable ODD format {C7}. EU Implementing Regulation 2022/1426 makes the ODD a legal requirement for fully automated vehicles: the ADS \"shall recognise its ODD conditions and boundaries of the ODD\" and \"shall detect and respond when one or more ODD conditions are not fulfilled or no longer fulfilled\", and the regulation lists the ODD conditions to be recognised, including precipitation, time of day, light intensity, fog and mist, road and lane markings, road category and geographical area {C37}."))
A(('p', "Surveys map the ODD research landscape {C3,C13}, and a recent mapping study of 120 research papers and 53 industry studies concludes that \"one ODD description is insufficient\" to support all use cases and identifies a lack of methods for ODD change management {C2}. Formalisation work defines operational domain and ODD formally but explicitly does not aim at a machine-readable specification, leaving that to ASAM OpenODD {D10}. Skoglund et al. specify ODDs in the Pkl configuration language using the ISO 34503 taxonomy; they state that their work does not develop a new taxonomy and that native traceability is lacking {C1}. Other work proposes ODD description methods judged by verifiability {C11}, taxonomies applied to specific services {C5}, and ties the ODD to the safety argument through strategies that keep the system within its ODD {C8}. Work on identifying the ODD from assessed risk {C12} and on extending the ODD to operational design conditions that include vehicle and occupant state {C13} moves towards deriving the ODD from safety analysis."))
A(('p', "Runtime monitoring asks whether the vehicle is currently inside its ODD. Torfah et al. learn monitors of the ODD for machine-learning-based systems through counterexample-guided refinement {C4}; other monitors predict failures from learned operating-condition models {D11} or combine runtime monitors for AI-based perception under SOTIF {D12}. These monitors are learned from data or scenario taxonomies rather than derived from stated requirements. The formal foundations of specification-based monitoring of cyber-physical systems are surveyed by Bartocci et al. {D51}."))
A(('p', "Across this literature, the ODD is specified, taxonomised, formalised and monitored, but no reviewed work derives ODD boundary predicates from natural-language safety requirements with trace links to their source. This is the gap Phase A addresses."))

A(('h2', "2.4 Scenario-Based Testing and Scenario Selection"))
A(('p', "Scenario-based testing distinguishes functional, logical and concrete scenarios across the development process {C17}, and ISO 34502:2022 provides a scenario-based safety evaluation framework {C27}. Surveys cover scenario-based safety assessment {C21}, scenario generation in general {D31,D33}, safety-critical scenario generation {D32}, simulation-based testing of autonomous cyber-physical systems {S29}, and virtual verification and validation toolchains {S6}. A study with industry partners identifies challenges of virtual validation and verification for automotive functions through a workshop and a survey {S9}. In a study with 50 participants, the out-of-bounds oracle used in simulation-based testing only partly matched human safety perception, which also depended on obstacles and on whether participants could interact with the vehicle {S30}, road features and vehicle dynamics affect which tests are cost-effective {S31}, and the gap between simulation and reality has been surveyed in robotics {S33}."))
A(('p', "Scenario languages and simulators make scenarios executable. Scenic is a probabilistic language for specifying scenarios and generating scenes {C22}, and CARLA is an open urban driving simulator {CARLA}. Requirements can drive test generation directly: Sim-ATAV writes requirements in Signal Temporal Logic and generates tests through covering arrays and robustness-guided falsification {C16}, and a systems approach generates test scenarios for automated driving systems systematically {C20}. Black-box safety validation algorithms more generally are surveyed by Corso et al. {D58}."))
A(('p', "For selecting scenarios, combinatorial testing gives the theoretical basis {D34}, and methods exist to measure the combinatorial coverage of test suites that are not covering arrays {KUHN13}. In the automated-driving domain, ontologies of the driving environment have been converted into combinatorial test suites {C32}, and an empirical comparison on two emergency-braking implementations found that strength-3 combinatorial testing gave the highest coverage and found all failure types, search-based testing found crashes faster, random testing had no clear advantage, and the two main approaches are \"complementary\" {C33}. These three methods therefore form the classical baselines for Phase B. The most recent work in the reviewed set that allocates tests on the basis of the ODD, by Skoglund et al., assigns existing test cases to test environments through rule-based matching on a formalised ODD, without optimisation {C9}."))

A(('h2', "2.5 From Natural-Language Requirements to Formal Specifications"))
A(('p', "Natural-language requirements are ambiguous, a problem surveyed by Shah and Jinwala {D22} and studied in case studies {D23}, with recent detection approaches based on SpanBERT and named-entity recognition {D24} and large language models in industry {D25}. The ISO/IEC/IEEE 29148 standard defines the characteristics of well-formed requirements {D54}, and the role of formalism in system requirements has been surveyed {S19}. Semantic approaches to requirements analysis {S15,S17} and data-driven elicitation {S16} are complementary lines of work."))
A(('p', "Automated formalisation is the closest methodological basis for Phase A. Req2Spec formalises natural-language requirements for the HANFOR tool and was evaluated on \"222 automotive domain software requirements at BOSCH, 71% of which were correctly formalized\" {C19}. NASA's FRET uses a structured natural language, FRETish, whose four fields (scope, condition, timing and response) are compiled into metric temporal logic {C34,C35}; the ODD boundary of a requirement typically sits in its condition field. DeepSTL translates English requirements into Signal Temporal Logic using grammar-generated training data and a transformer {C18}. A survey of requirement formalisation with large language models reports NL-to-LTL translation accuracy of up to 94.4% on public datasets {D14}. An agentic LLM approach to requirement formalisation reports 43.6% exact and 38.2% partial semantic matches in requirement extraction on 71 requirements from three cyber-physical scenarios {S20}. In safety engineering specifically, an LLM-based hazard analysis pipeline for automated driving treats restricting the ODD as one of its mitigation strategies (\"'Avoid being exposed to the situation' is one possibility, known today as the Operational Design Domain\") {D13}, and agent-based retrieval-augmented generation has been used to derive safety requirements for an automated driving stack {C10}."))
A(('p', "The pipeline components proposed for Phase A are ClausIE for clause-based information extraction {D60}, SciBERT for domain-adapted language modelling {D61} and Sentence-BERT for semantic similarity {D62}. Because large language models can produce fluent but unfounded output {D52}, and because machine-learning components need their own testing discipline {D45,D59}, the thesis uses LLM-based classification only as a baseline, not as the source of gold-standard labels."))

A(('h2', "2.6 From Natural Language to Test Scenarios"))
A(('p', "Three recent works generate driving scenarios from natural language and are the closest to the full pipeline of this thesis. ScenarioNL converts California DMV crash reports into executable Scenic programs simulated in CARLA, producing \"syntactically-correct programs at rates of up to 90%\" {C23}; publicly available crash and disengagement data of the kind it uses have been compiled by Sinha et al. {D64}. TARGET converts natural-language traffic rules from a driver handbook into CARLA test scenarios with an LLM, generating 217 scenarios that revealed about 700 rule violations, collisions and other issues {C24}. Jian et al. derive mandatory and prohibitive driving requirements from traffic law using a taxonomy that integrates OpenDRIVE and OpenSCENARIO concepts {C25}. A survey of large language models in scenario-based testing of automated driving systems reviews this emerging area {C26}."))
A(('p', "None of these works starts from safety requirements, extracts ODD boundary predicates, keeps trace links from requirement to scenario, or optimises which scenarios to run. They show that natural-language-to-scenario generation is feasible, and they provide the comparison points for the thesis's novelty claim."))

A(('h2', "2.7 Requirements Traceability"))
A(('p', "Gotel and Finkelstein's analysis of the requirements traceability problem {D46} and the later review of trends by Cleland-Huang et al. {D47} frame the field. In the automotive domain, traceability faces specific challenges {S41}; industrial reports show how traceability goes wrong in practice {S40}, why practitioners do not trace {S42}, and how traceability strategies are chosen per project {S67}. A three-year study at an automotive supplier found that \"consistency was less important in early development, but crucial right before a release\", and that traceability tools need versioning and change propagation {C28}. Recent work evaluates taxonomic trace links in an industrial case {S43}, recovers automotive requirement trace links with retrieval-augmented generation {S44}, reviews pre-requirements-specification traceability {S39}, and maps the effect of traceability on maintenance {S45}. RQ4 draws on this literature: a trace link is useful only if it survives requirement change."))

A(('h2', "2.8 Quantum Optimisation for Software Testing"))
A(('p', "QAOA was introduced by Farhi, Goldstone and Gutmann {D36}; QUBO and Ising formulations for many NP problems are catalogued by Lucas {D42}; and variational quantum algorithms are reviewed by Cerezo et al. {S51}. Quantum annealing is covered in a monograph by McGeoch {D37} and an industrial review by Yarkoni et al. {D38}, and its performance is measured on hardware with a time-to-target metric {D63}. Preskill's characterisation of the noisy intermediate-scale quantum (NISQ) era {D43} explains why advantage must be shown empirically. An independent evaluation concludes that for most optimisation problems \"while D-Wave can solve such problems, its performance has not yet matched that of its classical counterparts\" {D39}. QUBO formulations have been applied to vehicle routing {S65,S66}, and error mitigation for measurement is described by Nation et al. {S54}."))
A(('p', "In software engineering, a systematic survey of 77 studies on quantum optimisation found that 62.34% of solutions (48 of 77) are quantum-inspired algorithms run on classical computers and that 91.67% of reformulated problems are single-objective {D15}. Test optimisation is the most developed application. BootQA decomposes test case minimisation for quantum annealers by bootstrap sampling and achieves effectiveness similar to simulated annealing with better time efficiency on large problems {D19}. SelectQA reformulates regression test selection as a QUBO solved with D-Wave's hybrid solver and is reported as comparable to Additional Greedy and DIV-GA {C14}. IGDec-QAOA applies QAOA with decomposition to four industrial datasets on ideal and noisy simulators and IBM hardware; its authors state that it \"does not intend to demonstrate the quantum advantage\" {C15}. QAOA-based test case selection with K-means decomposition was evaluated on four SIR programs with a noiseless simulator, and its efficiency \"significantly declines\" for larger suites {D18}."))
A(('p', "The closest precedent for Phase B generates test cases for cyber-physical systems with quantum annealing and evaluates on a vehicle platoon and a pneumatic suspension system, comparing against simulated annealing and NSGA-II {D17}. Median fault detection was 82.6% for quantum annealing against 82.8% for simulated annealing and 83.0% for NSGA-II on the suspension system, and 73.0%, 73.7% and 74.2% on platooning, with no statistically significant differences (p > 0.05); median QPU access time was 3.57 s against 62.3 s and 75.2 s, although embedding took 40-45 s and the authors note that the approach is not ready for large problems without decomposition. Its lab package is publicly available, which allows its baseline to be reproduced. Quantum-for-automotive work beyond testing remains narrow: for example, a quantum neural network has been applied to traffic-light classification {D20}. Quantum software engineering more broadly addresses lifecycles {S59}, platforms {S57}, the definition of the discipline {S58}, bugs in quantum platforms {S60}, testing of quantum programs {S61} and verification of quantum circuits {S55,S62,D16}; these concern verifying quantum software, which is not the aim of this thesis."))

A(('h2', "2.9 Machine-Learning Safety, Standards and Assurance Cases"))
A(('p', "ISO/PAS 8800:2024 addresses safety and artificial intelligence in road vehicles {D57}, and UL 4600 covers the evaluation of autonomous products {D56}. Surveys cover artificial intelligence in safety-critical industrial and transportation systems {D55}, the challenges of machine learning in safety-critical cyber-physical systems {S47}, explainable AI for autonomous driving {D53} and for black-box models generally {S37,S38}, certified robustness of driving perception {D49} and adversarial robustness of LiDAR perception {D48}."))
A(('p', "Assurance cases connect evidence to safety claims. The Goal Structuring Notation {D26} is used in the Open Autonomy Safety Case Framework {D27}, in a framework for autonomous trains {D28} and in the model-based ACCESS approach {D29}. AMLAS integrates safety assurance into the development of machine-learning components and requires the operating environment to be explicitly defined {C29,C30}. The traceable predicate and scenario set produced by this thesis are candidate evidence for such arguments."))

A(('h2', "2.10 Synthesis and Research Gap"))
A(('p', "Table 2.1 compares the closest works against the four properties the thesis combines."))
A(('table', "Table 2.1. Closest works compared on the four properties the thesis combines (Y = yes, P = partly, N = no)",
   ["Work", "Starts from safety requirements", "Produces ODD boundary predicates", "Requirement-to-scenario traceability", "Optimised scenario selection"],
   [["Req2Spec {C19}", "Y", "N", "N", "N"],
    ["FRET {C34}", "Y", "N", "P (requirement to formula)", "N"],
    ["Sim-ATAV {C16}", "P (hand-written STL)", "N", "P", "P (falsification)"],
    ["Pkl ODD formalisation {C1}", "N", "P (formal ODD)", "P", "N"],
    ["ODD-based test allocation {C9}", "N", "P", "P", "N (rule matching)"],
    ["ScenarioNL {C23}", "N (crash reports)", "N", "N", "N"],
    ["TARGET {C24}", "N (traffic rules)", "N", "P (logs)", "N"],
    ["Quantum annealing test generation {D17}", "P (system requirements)", "N", "N", "Y (QUBO)"],
    ["This thesis", "Y", "Y", "Y", "Y (QUBO, compared with classical)"]],
   [2600, 1700, 1700, 1700, 1660]))
A(('p', "The Y/N/P classification reflects each work's published description as cited above. No reviewed work combines all four properties. The research gap is therefore a traceable path from stated safety requirements, through ODD boundary predicates, to an optimised and evaluated set of boundary scenarios. The most comprehensive mapping study of the ODD field to date {C2} does not address this combination, which confirms the originality of the research direction pursued in this thesis."))

A(('h2', "2.11 Summary of Reviewed Studies"))
A(('p', "Table 2.2 summarises the research studies discussed in this chapter: what each set out to find, how, what it found, its boundaries, and how it bears on this thesis. Standards, regulations and purely foundational works are cited in the text but not tabulated. Quoted phrases are taken from the cited source."))
import importlib.util as _u
_s=_u.spec_from_file_location('t22','table22.py'); _t=_u.module_from_spec(_s); _s.loader.exec_module(_t)
A(('table_land', "Table 2.2. Summary of research studies reviewed in Chapter 2",
   ["Citation & Year", "Research Objectives", "Methodology & Sample", "Key Findings", "Limitations", "Relevance & Research Gap"],
   [list(r) for r in _t.ROWS], [1500, 1900, 2400, 2700, 2000, 2460]))
A(('h2', "2.12 Limitations of the Review"))
A(('p', "This review adopts a focused scoping strategy. It prioritises depth at the intersection of four themes (ODD specification, requirement formalisation, scenario-based testing and quantum optimisation for software testing) over exhaustive coverage of each theme individually, and it is limited to English-language sources published between 2010 and 2026, together with earlier foundational works where they define concepts used in this thesis. Because quantum optimisation for software testing is a rapidly developing field, a small number of recent preprints are included where no peer-reviewed equivalent exists; these are identified as preprints in the reference list, and their findings are interpreted with corresponding caution. Standards and regulations are cited from their official catalogues and texts. Finally, the classification in Table 2.1 and the summaries in Table 2.2 are based on the published descriptions of each study and are therefore bounded by the level of detail those publications report."))
A(('pagebreak',))

# ---------------- Chapter 3 ----------------
A(('h1', "Chapter 3: Methodology"))
A(('h2', "3.1 Research Paradigm and Design"))
A(('p', "The thesis follows design science research: it builds artefacts (the corpus, the extraction method and the QUBO formulation) and evaluates them against defined criteria. The evaluation is experimental and comparative: each artefact is compared with published baselines on fixed metrics, anchored by a case study reconstructed from public records."))

A(('h2', "3.2 Requirements Corpus"))
A(('p', "Phase A is evaluated on real requirements only. The first source is EU Implementing Regulation 2022/1426 {C37}. Its Annex II contains the performance requirements for the automated driving system, including the ODD requirements quoted in Section 2.3; its Annex III contains the assessment provisions. An extraction script recorded 370 points verbatim with their annex and point numbers: all 141 numbered points of Annex II (91 containing \"shall\" or \"must\" and 50 context points such as the list of ODD conditions) and the 229 normative points of Annex III. UN Regulation No. 157 on Automated Lane Keeping Systems {C38} is the second source, and the PURE dataset of 79 public requirements documents {C36} supplies non-automotive requirements for negative examples. Requirements written by the researcher, including those used in the feasibility study, are excluded from evaluation."))
A(('p', "Each requirement is annotated for whether it contains an ODD condition and, if so, its dimension, variable, operator, threshold, unit and required response. Annotation reads each requirement through FRET's scope, condition, timing and response fields {C34}. The dimension schema comprises the ODD conditions enumerated in EU 2022/1426 Annex II point 3.1.4.1, supplemented by speed, traffic participants, temperature and a \"generic\" category for requirements that refer to the ODD as a whole, and its labels are aligned with the taxonomies of ISO 34503 {C6} and PAS 1883 {D66}."))
A(('p', "Two annotators label the corpus independently after a calibration round on 20 requirements. Agreement is reported with Cohen's kappa {COHEN} for the categorical fields and exact-match percentage for variable, operator, threshold and unit. Disagreements are resolved by discussion or by the supervisor as a third annotator. No AI system acts as annotator. The corpus is split 60/20/20 into training, development and test sets, stratified by source and fixed before any model is built, with an additional held-out-source evaluation."))

A(('h2', "3.3 Phase A: Requirement to Traceable ODD Boundary Predicate"))
A(('p', "Phase A follows the architecture of Req2Spec {C19}. Clause-level extraction with ClausIE {D60} isolates the condition clause; a SciBERT-based classifier {D61} assigns the ODD dimension; Sentence-BERT embeddings {D62} match variables to taxonomy entries; and a rule layer extracts operator, threshold and unit. The output for each requirement is a record of the form requirement identifier, ODD dimension, boundary predicate, response, stored so that a change to the requirement can be propagated to every predicate and scenario that depends on it. Where useful, predicates can be exported in the ASAM OpenODD format {C7}."))
A(('p', "Baselines are the rule-based and TF-IDF extractors from the feasibility study (Chapter 4) and zero-shot classification with a large language model. Results are reported as precision, recall and F1 per field on the test split, and compared with Req2Spec's 71% {C19} as a reference point for a related but different task."))

A(('h2', "3.4 Phase B: ODD Predicate to QUBO Scenario Selection"))
A(('p', "Phase B adapts the pipeline of the closest precedent {D17}. First, seed scenarios are generated as logical scenarios {C17} parameterised by the ODD dimensions extracted in Phase A, for example a vehicle approaching a visibility boundary at a given speed with a given pedestrian exposure. Second, selecting scenarios is formulated as a QUBO {D42} with terms for effectiveness, diversity, set size, dimension coverage and a traceability weight that favours scenarios exercising a predicate derived from a stated requirement. Third, large problems are decomposed into sub-problems that fit the hardware, following the decomposition strategies used in BootQA {D19}, IGDec-QAOA {C15} and QAOA-based selection {D18}."))
A(('p', "The QUBO is solved with quantum annealing and with QAOA {D36}. Baselines are random sampling, combinatorial testing, search-based testing {C33}, a greedy coverage heuristic, simulated annealing and NSGA-II, so that results are comparable with both the automated-driving testing literature and the quantum precedent. The precedent's public lab package is used first to reproduce its baseline. Selected scenarios are executed in CARLA {CARLA}, written as Scenic programs {C22}, against a reconstructed fault model of the EA26002 visibility case {D2}."))

A(('h2', "3.5 Evaluation Plan"))
A(('table', "Table 3.1. Research questions, metrics and baselines",
   ["RQ", "Metrics", "Baselines / reference", "Statistical treatment"],
   [["RQ1", "Precision, recall and F1 per annotated field; agreement with gold labels on the test split and held-out source", "Rule-based, TF-IDF and LLM zero-shot extractors; Req2Spec 71% as reference", "95% confidence intervals by bootstrap"],
    ["RQ2", "ODD dimension-combination coverage; input and output diversity; fault detection on the reconstructed fault model", "Random, combinatorial, search-based, greedy, simulated annealing, NSGA-II", "Wilcoxon or Mann-Whitney tests over repeated runs; effect sizes"],
    ["RQ3", "Wall-clock time; QPU access time; embedding time; qubits; problem size at which decomposition is required", "Same as RQ2", "Scaling curves over problem size"],
    ["RQ4", "Share of selected scenarios with an unbroken trace to a source requirement; correctness of change propagation after a requirement edit", "Manual trace audit", "Descriptive, with every broken link listed"]],
   [700, 3200, 3000, 2460]))
A(('p', "**Threats to validity.** The case study is a reconstruction from public information. Simulator results may not hold on noisy hardware. The corpus is drawn from regulations, whose wording may differ from manufacturers' internal requirements. The held-out-source evaluation and the full reporting of all outcomes, including non-significant differences, are the principal mitigations."))
A(('h2', "3.6 Ethics and Research Integrity"))
A(('p', "The second annotator takes part with informed consent, following COMSATS procedures. The case study uses only public regulatory records. All experimental figures are produced by version-controlled code and data that are archived with the thesis. The use of generative AI tools is set out in the Declaration at the front of this thesis, in accordance with university policy; no AI system provides gold-standard labels or evaluation results."))
A(('pagebreak',))

# ---------------- Chapter 4 ----------------
A(('h1', "Chapter 4: Preliminary Feasibility Study"))
A(('p', "Before constructing the corpus and experimental framework described in Chapter 3, I conducted a small-scale feasibility study to establish whether both phases could be realised with openly available tools and to identify design requirements early. The study deliberately used small samples: 15 development and 25 held-out requirement sentences written for the study, and 10 candidate scenarios. Its results are therefore indicative rather than confirmatory; they informed the design decisions in Chapter 3, and the full evaluation on the real-requirements corpus is reported in Chapter 5."))
A(('h2', "4.1 Phase A: Predicate Extraction"))
A(('p', "A rule-based extractor was written from 15 sentences and scored on the same sentences: 93.3% correct ODD dimension (14 of 15) and 80.0% fully correct including the predicate (12 of 15). On 25 new sentences scored without adjustment, dimension accuracy fell to 32.0% and full correctness to 28.0%. A TF-IDF similarity classifier built from the 15 training sentences scored 28.0% on the same 25. Zero-shot classification of the 25 sentences by a large language model assigned the dimension correctly in 24 cases (96.0%); the one disagreement concerned a daylight-only restriction that could be read as a lighting or a time condition."))
A(('table', "Table 4.1. Phase A feasibility-study results",
   ["Method", "Evaluation set", "Result", "Limitation"],
   [["Rule-based", "15 sentences it was written from", "93.3% dimension; 80.0% full", "Fit to its own sentences"],
    ["Rule-based", "25 unseen sentences", "32.0% dimension; 28.0% full", "Small sample"],
    ["TF-IDF similarity", "25 unseen sentences", "28.0%", "15 training sentences across 9 categories"],
    ["LLM zero-shot", "25 unseen sentences", "96.0% dimension (24 of 25)", "Single annotator; dimension only, not thresholds"]],
   [1800, 2600, 2400, 2560]))
A(('p', "Two findings shaped the method adopted in Chapter 3. First, the drop from 80% to 28% shows that rules fitted to a handful of sentences do not generalise, which motivates a trained pipeline and a real corpus. Second, the LLM result cannot serve as evidence of accuracy, because the gold labels were written by a single person and the task covered only the dimension; Chapter 3 therefore uses two independent human annotators and restricts LLMs to a baseline role."))
A(('h2', "4.2 Phase B: QUBO Scenario Selection"))
A(('p', "Ten candidate scenarios covering six ODD sub-dimensions were formulated as a QUBO with terms for effectiveness, pairwise diversity and a target of four scenarios, and solved by random sampling (200 trials), a greedy coverage heuristic, simulated annealing and a one-layer QAOA circuit with fixed parameters on a statevector simulator. Without a coverage term, random search, simulated annealing and QAOA converged to the same solution (objective -15.33), covering four of six dimensions, while greedy covered all six with a worse objective (-11.75). The objective did not reward coverage. With a coverage bonus and a redundancy penalty, simulated annealing and QAOA covered five of six dimensions and greedy six of six; QAOA's untuned parameters selected six scenarios instead of four. Variational optimisation of the QAOA parameters was outside the scope of this study and forms part of Phase B."))
A(('table', "Table 4.2. Phase B feasibility-study results (10 scenarios, simulators)",
   ["Method", "Dimensions covered (no coverage term)", "Dimensions covered (with coverage term)"],
   [["Random sampling (200 trials)", "4 of 6", "4 of 6"],
    ["Greedy coverage heuristic", "6 of 6", "6 of 6"],
    ["Simulated annealing", "4 of 6", "5 of 6"],
    ["QAOA, 1 layer, fixed parameters", "4 of 6", "5 of 6 (selected 6 scenarios, target 4)"]],
   [3400, 2980, 2980]))
A(('p', "The feasibility study supports no claim of quantum advantage. It shows that the formulation must reward coverage explicitly and that QAOA parameters must be tuned, both of which are built into Phase B."))

