# Table 2.2 rows: (citation, objectives, method & sample, key findings, limitations, relevance & gap)
ROWS = [
# --- Formal verification and safety definitions
("Mitra et al., 2025 {D8}", "Survey formal verification techniques for vision-based autonomous systems.", "Literature survey organised into six technique families (probabilistic abstraction, perception contracts, compositional verification, camera/environment models, generative models, statistical model checking/runtime verification).", "\"A DNN can have billions of parameters, which precludes formal verification for most realistic, state-of-the-art networks\"; one camera-based technique takes \"about an hour\" for its largest environments.", "Survey only; assurances hold \"only\" within a narrow operational design domain.", "Shows why full verification is intractable and why the ODD boundary is the right target for this thesis."),
("Shalev-Shwartz et al., 2017 {D67}", "Define a formal, interpretable safety model for automated driving.", "Mathematical model (Responsibility-Sensitive Safety) plus a system design argument.", "Proposes \"a white-box, interpretable, mathematical model for safety assurance\".", "Covers driving behaviour for specifiable manoeuvres, not perception or operating-condition boundaries.", "Shows formal guarantees are possible for narrow behaviour; the ODD boundary remains open."),
# --- ODD
("Skoglund et al., 2025 {C1}", "Make ODD specifications machine-readable and exchangeable.", "ODD formalised in the Pkl configuration language using the ISO 34503 taxonomy; automotive example.", "Formal, validated ODD configuration; test-scenario allocation named as future work.", "Does not develop a taxonomy; \"native traceability is lacking\".", "Closest ODD formalisation; lacks derivation from requirements and trace links, which Phase A provides."),
("Skoglund et al., 2025 {C9}", "Allocate test cases to suitable test environments using a formalised ODD.", "Pkl ODD extended with test-environment attributes; rule-based comparison (\"genericCompare\"); reversing-truck case study.", "Automated matching of scenario needs to simulation and HIL environment capabilities.", "Rule matching, no optimisation; does not start from natural-language requirements; single case study.", "Nearest neighbour to Phase B; this thesis contributes requirement-derived predicates and optimised selection."),
("Hillen et al., 2025 {C2}", "Map research and practice on ODDs for automated driving.", "Mapping study of 120 research papers and 53 industry studies around four research questions.", "\"One ODD description is insufficient\" for all use cases; lack of methods for ODD change management.", "Does not cover deriving ODDs from safety requirements or quantum optimisation.", "Most comprehensive ODD mapping study; it does not address requirement-derived ODDs, and it identifies change management (RQ4) as an open problem."),
("Torfah et al., 2022 {C4}", "Learn runtime monitors that detect when ML-based systems leave their ODD.", "Counterexample-guided refinement and conformance testing; evaluated on autonomous driving scenarios.", "Framework for learning monitorable ODDs for assured autonomy.", "ODD boundary is learned from data, not derived from stated requirements.", "Contrasting route to ODD boundaries; Phase A derives them from requirements instead."),
("Xu et al., 2025 {D11}", "Predict failures by learning Operational Design Condition boundaries.", "ODCNet (Mamba2 state-space modules with Bayesian inference and Gaussian-process calibration); three case studies (intersection, lane keeping, vehicle detection) on AV test records.", "Precision 0.889, recall 0.754, F-score 0.901 on intersection data.", "Authors: long-term ODC/ODD prediction \"remains limited\"; boundaries learned from data.", "Learned boundaries without requirement traceability, the gap Phase A targets."),
("Schaller et al., 2026 {D12}", "Integrate runtime monitor ensembles for AI perception into SOTIF processes.", "Conceptual integration of complementary monitors into the ISO 21448 lifecycle and safety argument.", "Monitors address uncertainty sources such as disagreement between redundant systems and unfamiliar activation patterns.", "Emphasises lifecycle integration rather than implementation details.", "Runtime side of ODD assurance; complementary to design-time scenario selection."),
("Gyllenhammar et al., 2020 {C8}", "Define an ODD that supports the safety argument of an ADS.", "Conceptual method using use cases mapped to operating conditions.", "Four generic strategies to keep the system within its ODD; modular ODD supporting continuous delivery.", "Conceptual; no automated extraction or evaluation.", "Links the ODD to safety requirements and argumentation, as Phase A does automatically."),
("Mendiboure et al., 2023 {C5}", "Define a generic ODD taxonomy and apply it.", "Analysis of existing taxonomies; application to the BuSAS bus-station service on the Satory test track.", "Six-category taxonomy (physical infrastructure, scenery, environmental conditions, traffic conditions, digital infrastructure, vehicle capabilities).", "Single use case.", "Candidate taxonomy for Phase A's target schema alongside ISO 34503 and PAS 1883."),
("Xu et al., 2026 {C13}", "Review the Operational Design Condition (ODC) framework.", "Comprehensive literature review.", "ODC extends the ODD with driver/passenger and vehicle state; closed-loop ODC development with hazard analysis, monitoring and extension.", "Review; no new empirical evaluation.", "Supports deriving operating conditions from hazard analysis, the direction Phase A takes."),
# --- Scenario-based testing
("Menzel et al., 2018 {C17}", "Define scenario notions for developing and testing automated vehicles.", "Conceptual analysis across the ISO 26262 process.", "Functional, logical and concrete scenario abstraction levels.", "Conceptual.", "Phase B's seed scenarios are logical scenarios in this sense."),
("Riedmaier et al., 2020 {C21}", "Survey scenario-based safety assessment of automated vehicles.", "Literature survey with a new taxonomy.", "Selecting representative scenarios from an effectively infinite space is a central challenge; proposes combining scenario-based testing with formal verification.", "Survey only.", "Motivates optimised scenario selection (Phase B)."),
("Amersbach and Winner, 2019 {C31}", "Determine the scenario coverage needed for validation of highly automated vehicles.", "Analytical approach converting required test distance into required scenarios.", "Gap of \"around one order of magnitude\" between required and feasible test coverage.", "Estimation approach; points to combining with other methods.", "Quantitative case for selecting fewer, better scenarios."),
("Tuncali et al., 2019 {C16}", "Generate tests for AVs with ML components from formal requirements.", "Sim-ATAV: requirements in Signal Temporal Logic; covering arrays and robustness-guided falsification; three driving scenarios with camera, lidar, radar and a DNN detector.", "Finds critical behaviours from collision risks to sensor failures propagating to system faults.", "Requirements written by hand in STL; no ODD mapping.", "Requirement-driven testing precedent; the thesis starts from natural language and ODD predicates."),
("Khastgir et al., 2021 {C20}", "Create test scenarios for ADS systematically.", "Systems approach to scenario creation.", "Argues that the types of scenarios matter more than test mileage.", "No optimisation of the resulting scenario set.", "Classical route from safety analysis to scenarios."),
("Li et al., 2020 {C32}", "Generate tests for automated driving functions from environment ontologies.", "Two algorithms converting ontologies into combinatorial test cases; case study in simulation.", "Practical combinatorial testing of automated driving functions.", "Ontology written by experts, not derived from requirements.", "Combinatorial baseline family for Phase B."),
("Klück et al., 2023 {C33}", "Compare combinatorial and search-based testing for automated driving.", "Empirical comparison on two emergency-braking implementations; combinatorial (strength 3), search-based and random testing.", "Combinatorial testing had the highest coverage and found all failure types; search-based testing found crashes faster; random had no clear advantage; methods are \"complementary\".", "Two implementations of one function.", "Defines the classical baselines Phase B must match."),
("Birchler et al., 2024 {S30}", "Check whether simulation-based test verdicts match human perception.", "Study with 50 participants in virtual reality; test cases from BeamNG.tech and CARLA.", "The out-of-bounds oracle only partly matched human safety perception, which also depended on obstacles and interaction.", "Mostly academic participants; two simulators; one oracle.", "Caution for Phase B fault-detection oracles in simulation."),
("Cabrero-Daniel and Mohamad, 2025 {S9}", "Identify challenges of virtual validation and verification of automotive functions.", "Workshop (7 participants) and survey (10 respondents from 9 partner organisations, including 4 automotive companies).", "Challenges and solutions of virtual V&V from industry and research perspectives.", "Small qualitative sample.", "Industrial context for simulation-based scenario testing."),
# --- Requirements formalisation
("Nayak et al., 2022 {C19}", "Transform natural-language requirements into formal specifications.", "Req2Spec NLP pipeline producing HANFOR specifications; 222 automotive requirements at Bosch.", "\"71% of which were correctly formalized\".", "General requirement formalisation, not specific to ODD conditions.", "Architectural basis for Phase A; 71% is the reference point for RQ1."),
("Giannakopoulou et al., 2021 {C34}", "Formalise structured natural-language requirements automatically.", "FRETish language with scope, condition, timing and response fields compiled to metric temporal logic; applied to Lockheed Martin CPS requirements.", "Future- and past-time formulas generated; equivalence checked by automated verification; open-source FRET tool.", "Requires writing requirements in a restricted language.", "Provides the field structure used in the Phase A annotation guideline."),
("He et al., 2022 {C18}", "Translate English requirements into Signal Temporal Logic.", "Grammar-based synthetic training data and transformer translation (DeepSTL).", "High translation quality for well-trained requirement patterns.", "Quality depends on patterns seen in training.", "Alternative learned translator; comparison point for Phase A."),
("Tagliaferro et al., 2026 {S20}", "Formalise requirements from unstructured specifications with an agentic LLM.", "LLM agents; 71 requirements from three cyber-physical scenarios.", "43.6% exact and 38.2% partial semantic match in extraction; 88.7% verifiability accuracy; 77.8% effective semantic translation.", "Small preprint study; three cyber-physical scenarios.", "Shows LLM formalisation is feasible but imperfect; supports using LLMs as baseline only."),
("Nouri et al., 2024 {D13}", "Use LLMs to engineer safety requirements for autonomous driving.", "LLM-based hazard analysis and risk assessment pipeline; evaluated through expert interviews.", "Experts found LLM-generated safety requirements \"comparable to human-written results\"; ODD restriction appears as a mitigation strategy.", "Human oversight remains essential.", "Upstream source of ODD-related safety requirements for Phase A."),
("Balu et al., 2025 {C10}", "Derive safety requirements automatically with agent-based RAG.", "Agent-based retrieval-augmented generation over safety standards; Apollo ADS.", "Higher retrieval precision than default RAG.", "Similarity metrics barely separate the two approaches.", "Another upstream route to safety requirements."),
("Bashir et al., 2025 {D25}", "Detect and explain requirement ambiguity with LLMs in industry.", "Three open LLMs; 663 requirements from Westermo and Alstom; 0- to 10-shot prompting; 8 experts rated explanations.", "10-shot prompting gave a 20.2% average improvement over 0-shot; explanations rated 3.84/5.", "Authors: results \"may not be generalizable beyond the studied contexts\"; weak domain terminology.", "Ambiguity is a risk for Phase A extraction; LLMs need examples and oversight."),
("Talha et al., 2025 {D24}", "Detect ambiguities in software requirements semi-automatically.", "SpanBERT with named-entity recognition; 425 functional requirements from 16 domains.", "Outperformed ChatGPT at detecting anaphoric, coordination and missing-condition ambiguity.", "General requirements, not automotive safety.", "Missing-condition ambiguity bears directly on extracting ODD conditions."),
("Menghi et al., 2021 {S63}", "Provide specification patterns for robotic missions.", "Pattern catalogue from 245 mission requirements; evaluated on 441 real requirements and 1,251 specifications.", "About 92% of the collected specifications expressible with the patterns.", "Robotics missions, not automotive ODDs.", "Pattern-based formalisation as a precedent for structured predicates."),
# --- NL to scenarios
("Elmaaroufi et al., 2024 {C23}", "Generate probabilistic scenario programs from natural language.", "ScenarioNL: California DMV crash reports converted into Scenic programs simulated in CARLA.", "Syntactically correct programs at rates \"up to 90%\"; composite score 4.3 against 2.0-3.6 for baselines.", "Input is crash reports; no ODD predicates, traceability or selection.", "Closest end-to-end neighbour; the thesis starts from safety requirements and optimises selection."),
("Deng et al., 2023 {C24}", "Generate test scenarios from traffic rules.", "TARGET: LLM parses 98 rules from a driver handbook into CARLA scenarios.", "217 scenarios on 8 maps revealed about 700 violations and collisions; 90 of 98 rules parsed with full accuracy.", "Traffic rules, not safety requirements; no ODD boundaries or optimisation.", "Shows natural-language-to-scenario generation is feasible."),
("Jian et al., 2026 {C25}", "Derive driving requirements from traffic laws.", "LLM with taxonomy-guided anchoring over a 227-node taxonomy integrating OpenDRIVE/OpenSCENARIO; field tests with 20 AVs.", "Law-scenario matching F1 0.804 against 0.513 for baselines.", "Preprint; limited explicit ODD mapping.", "Taxonomy-anchored extraction with traceability, methodologically close to Phase A."),
# --- Traceability
("Wohlrab et al., 2020 {C28}", "Understand how traceability should evolve in automotive development.", "Three-year case study at an automotive supplier.", "\"Consistency was less important in early development, but crucial right before a release\"; tools need versioning and change propagation.", "Single company.", "Evidence for RQ4: traces must survive change."),
("Niu et al., 2025 {S44}", "Validate and recover automotive requirement trace links.", "TVR with retrieval-augmented generation; 1,320 stakeholder and 48 system requirements with 2,132 links.", "98.87% validation accuracy and 85.50% recovery correctness; 502 missing links found.", "Single industrial project; data not public.", "Post-hoc recovery; the thesis creates trace links at extraction time."),
# --- Quantum
("Zhang et al., 2026 {D15}", "Survey quantum optimisation in software engineering.", "Systematic literature review of 77 studies covering 32 software-engineering problems.", "62.34% of solutions are quantum-inspired on classical hardware; 91.67% of reformulated problems are single-objective.", "Survey; field dominated by classical simulation.", "Positions Phase B and warns against claiming advantage from simulation."),
("Araujo et al., 2025 {D17}", "Generate test cases for cyber-physical systems with quantum annealing.", "QUBO formulation on D-Wave; vehicle platoon and pneumatic suspension; compared with simulated annealing and NSGA-II.", "Fault detection 82.6% against 82.8% and 83.0% (suspension), no significant differences (p > 0.05); QPU access 3.57 s against 62.3 s and 75.2 s.", "Embedding took 40-45 s; only two systems; not ready for large problems without decomposition.", "Closest Phase B precedent; its public lab package lets the thesis reproduce the baseline."),
("Wang et al., 2024 {D19}", "Minimise test suites with quantum annealers.", "BootQA: bootstrap-sampling decomposition and a QUBO with execution time and failure rate; three datasets (89 to 1,663 tests).", "Effectiveness similar to simulated annealing; better time efficiency on large problems.", "Relies on decomposition for hardware limits.", "Decomposition strategy for Phase B."),
("Trovato et al., 2025 {C14}", "Reformulate regression test optimisation with quantum annealing.", "SelectQA: QUBO solved with D-Wave's hybrid solver; compared with BootQA, Additional Greedy and DIV-GA.", "More effective than BootQA; comparable to Additional Greedy and DIV-GA.", "Uses a hybrid classical-quantum solver.", "QUBO test-selection precedent; baselines for Phase B."),
("Trovato et al., 2025 {D18}", "Investigate QAOA for test case selection.", "QAOA with K-means decomposition; four SIR programs (flex, grep, gzip, sed); noiseless statevector simulator.", "Outperformed baselines and SelectQA in effectiveness.", "Simulator only; efficiency \"significantly declines\" for larger suites.", "QAOA route for Phase B with the same decomposition problem."),
("Wang et al., 2023 {C15}", "Apply QAOA to test case optimisation.", "IGDec-QAOA on four industrial datasets (90 to 5,555 tests); ideal and noisy simulators and IBM hardware.", "Comparable to classical approaches; beat GA on two of five problems.", "Authors: does \"not intend to demonstrate the quantum advantage\".", "Model for transparent reporting and hardware execution in Phase B."),
("Quinton et al., 2025 {D39}", "Assess quantum annealing against classical solvers.", "Comparative evaluation of D-Wave on optimisation problems.", "\"Its performance has not yet matched that of its classical counterparts\"; hybrid solver most promising for integer quadratic objectives.", "General optimisation problems, not test selection.", "Independent caution against assuming quantum advantage in Phase B."),
("King et al., 2015 {D63}", "Benchmark a quantum annealer against classical solvers.", "Time-to-target metric on D-Wave 2X; problems of 128 to 1,097 qubits.", "2x to 15x faster than single-threaded classical software including I/O.", "Vendor study; specific problem classes and 2015 hardware.", "Defines a time-based metric usable for RQ3."),
("Innan et al., 2024 {D20}", "Classify traffic-light states with a quantum neural network.", "QNN with quantum image encodings; CARLA and cropped LISA datasets.", "97.42% accuracy on CARLA data and 84.08% on cropped LISA.", "Perception task only; noise sensitivity varies by noise type.", "Shows quantum work in driving is mostly perception, not testing."),
# --- Assurance and data
("Paterson et al., 2025 {C29}", "Provide a methodology for assuring ML components in autonomous systems.", "AMLAS lifecycle with safety-case argument patterns; examples across healthcare, automotive and aerospace.", "First methodology integrating safety assurance into ML component development.", "Guidance-level; relies on explicitly defined operating environments.", "The thesis's traceable predicates and scenarios are candidate evidence for such arguments."),
("Sinha et al., 2021 {D64}", "Make California AV crash and disengagement data usable for research.", "Processed DMV disengagement data (2014-2019) and crash data to March 2020, with OpenStreetMap context.", "Standardised public dataset of AV incidents.", "Limited to California reports and their reporting format.", "Candidate data for validating ODD extraction on incident narratives."),
]
